FROM malmopy-cntk-cpu-py27:latest

RUN mkdir /root/malmo-challenge/ai_challenge/danish_puppeteers

# Copy over private key, and set permissions
ADD . /root/malmo-challenge/ai_challenge/danish_puppeteers
